- src: git+git@github.com:EvilGn0me/nginx-role.git
- src: git+git@github.com:EvilGn0me/php-role.git
- src: git+git@github.com:EvilGn0me/mariadb-role.git
- src: git+git@github.com:EvilGn0me/zabbix-server-role.git
- src: git+git@github.com:EvilGn0me/zabbix-agent-role.git
